name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [
          {"version": 11, "extra": "-Pnative -Dquarkus.native.container-build=true"},
          {"version": 17, "extra": "-pl !chapter-2/thorntail-hello"}
        ]
    name: Build with jdk ${{matrix.java.version}}
    steps:
      - uses: actions/checkout@v4
        name: checkout
      - uses: actions/setup-java@v3
        name: set up jdk ${{matrix.java.version}}
        with:
          distribution: temurin
          java-version: ${{matrix.java.version}}
          cache: maven
      - name: Build
        run: mvn -B clean verify ${{matrix.java.extra}}
